BEGIN;
CREATE SCHEMA dw;
SET search_path TO dw, public;
 
-- Dimensiones
CREATE TABLE dim_tiempo (
 sk_tiempo integer PRIMARY KEY,
 fecha date NOT NULL UNIQUE,
 anio smallint NOT NULL,
 numero_semestre smallint NOT NULL CHECK(numero_semestre IN (1,2)),
 codigo_periodo varchar(10) NOT NULL,
 mes smallint NOT NULL CHECK(mes BETWEEN 1 AND 12),
 nombre_mes varchar(15) NOT NULL,
 dia smallint NOT NULL CHECK(dia BETWEEN 1 AND 31));
CREATE TABLE dim_curso (
 sk_curso integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_curso_origen integer NOT NULL UNIQUE,
 codigo varchar(12) NOT NULL, nombre varchar(100) NOT NULL,
 creditos smallint NOT NULL CHECK(creditos BETWEEN 1 AND 12));
CREATE TABLE dim_sede (
 sk_sede integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_sede_origen integer NOT NULL UNIQUE, nombre varchar(80) NOT NULL);
CREATE TABLE dim_horario (
 sk_horario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_horario_origen integer NOT NULL UNIQUE, franja varchar(30) NOT NULL);
CREATE TABLE dim_estudiante (
 sk_estudiante integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_estudiante_origen integer NOT NULL UNIQUE,
 alias varchar(30) NOT NULL,
 carrera varchar(100) NOT NULL,
 cohorte varchar(10) NOT NULL,
 anio_ingreso smallint);
CREATE TABLE dim_grupo (
 sk_grupo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_grupo_origen integer NOT NULL UNIQUE,
 numero_grupo smallint CHECK(numero_grupo > 0),
 docente varchar(50) NOT NULL,
 modalidad varchar(30) NOT NULL);
 
-- Miembro No aplica (sk = -1) para las filas donde la dimensión no existe
INSERT INTO dim_estudiante(sk_estudiante,id_estudiante_origen,alias,carrera,cohorte,anio_ingreso) VALUES (-1,-1,'No aplica','No aplica','N/A',NULL);
INSERT INTO dim_grupo(sk_grupo,id_grupo_origen,numero_grupo,docente,modalidad) VALUES (-1,-1,NULL,'No aplica','No aplica');
 

CREATE TABLE fact_academico (
 sk_hecho integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tipo_registro varchar(10) NOT NULL CHECK(tipo_registro IN ('SOLICITUD','GRUPO')),
 id_solicitud_origen integer UNIQUE,
 id_matricula_origen integer UNIQUE,
 sk_tiempo integer NOT NULL REFERENCES dim_tiempo,
 sk_estudiante integer NOT NULL REFERENCES dim_estudiante,
 sk_curso integer NOT NULL REFERENCES dim_curso,
 sk_sede integer NOT NULL REFERENCES dim_sede,
 sk_horario integer NOT NULL REFERENCES dim_horario,
 sk_grupo integer NOT NULL REFERENCES dim_grupo,
 solicitudes smallint NOT NULL CHECK(solicitudes IN (0,1)),
 es_asignada smallint NOT NULL CHECK(es_asignada IN (0,1)),
 es_sin_cupo smallint NOT NULL CHECK(es_sin_cupo IN (0,1)),
 es_no_elegible smallint NOT NULL CHECK(es_no_elegible IN (0,1)),
 es_desistida smallint NOT NULL CHECK(es_desistida IN (0,1)),
 matricula smallint NOT NULL CHECK(matricula IN (0,1)),
 es_aprobado smallint NOT NULL CHECK(es_aprobado IN (0,1)),
 es_reprobado smallint NOT NULL CHECK(es_reprobado IN (0,1)),
 es_retirado smallint NOT NULL CHECK(es_retirado IN (0,1)),
 nota numeric(5,2) CHECK(nota IS NULL OR nota BETWEEN 0 AND 100),
 creditos_aprobados smallint NOT NULL DEFAULT 0 CHECK(creditos_aprobados >= 0),
 grupos smallint NOT NULL CHECK(grupos IN (0,1)),
 capacidad_corte smallint NOT NULL DEFAULT 0 CHECK(capacidad_corte >= 0),
 CHECK(solicitudes + grupos = 1),
 CHECK((tipo_registro='SOLICITUD' AND solicitudes=1 AND id_solicitud_origen IS NOT NULL
        AND es_asignada+es_sin_cupo+es_no_elegible+es_desistida=1 AND capacidad_corte=0
        AND ((sk_grupo <> -1) = (matricula=1)))
    OR (tipo_registro='GRUPO' AND grupos=1 AND sk_grupo <> -1 AND id_solicitud_origen IS NULL
        AND id_matricula_origen IS NULL AND capacidad_corte>0 AND matricula=0)),
 CHECK(matricula = es_asignada),
 CHECK(es_aprobado+es_reprobado+es_retirado <= matricula),
 CHECK((id_matricula_origen IS NOT NULL) = (matricula=1)));
CREATE UNIQUE INDEX ux_fact_grupo ON fact_academico(sk_grupo) WHERE tipo_registro='GRUPO';
COMMIT;
 
