CREATE SCHEMA dw;
SET search_path TO dw, public;
 
-- Dimensiones
CREATE TABLE dim_tiempo (
 sk_tiempo integer PRIMARY KEY,
 fecha date NOT NULL UNIQUE,
 anio smallint NOT NULL,
 numero_semestre smallint NOT NULL CHECK(numero_semestre IN (1,2)),
 codigo_periodo varchar(10) NOT NULL,
 mes smallint NOT NULL CHECK(mes BETWEEN 1 AND 12),
 nombre_mes varchar(15) NOT NULL,
 dia smallint NOT NULL CHECK(dia BETWEEN 1 AND 31));
CREATE TABLE dim_curso (
 sk_curso integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_curso_origen integer NOT NULL UNIQUE,
 codigo varchar(12) NOT NULL, nombre varchar(100) NOT NULL,
 creditos smallint NOT NULL CHECK(creditos BETWEEN 1 AND 12));
CREATE TABLE dim_sede (
 sk_sede integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_sede_origen integer NOT NULL UNIQUE, nombre varchar(80) NOT NULL);
CREATE TABLE dim_horario (
 sk_horario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_horario_origen integer NOT NULL UNIQUE, franja varchar(30) NOT NULL);
CREATE TABLE dim_docente (
 sk_docente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_docente_origen integer NOT NULL UNIQUE, alias varchar(50) NOT NULL);
CREATE TABLE dim_modalidad (
 sk_modalidad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_modalidad_origen integer NOT NULL UNIQUE, nombre varchar(30) NOT NULL);
CREATE TABLE dim_carrera (
 sk_carrera integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_carrera_origen integer NOT NULL UNIQUE, nombre varchar(100) NOT NULL);
CREATE TABLE dim_cohorte (
 sk_cohorte integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cohorte varchar(10) NOT NULL UNIQUE,
 anio_ingreso smallint NOT NULL, semestre_ingreso smallint NOT NULL CHECK(semestre_ingreso IN (1,2)));
CREATE TABLE dim_estudiante (
 sk_estudiante integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_estudiante_origen integer NOT NULL UNIQUE, alias varchar(30) NOT NULL);
 
-- Hecho 1: una fila por matrícula efectiva al corte
CREATE TABLE fact_matricula (
 id_matricula_origen integer PRIMARY KEY,
 id_solicitud_origen integer NOT NULL UNIQUE,
 id_grupo_origen integer NOT NULL,
 sk_tiempo integer NOT NULL REFERENCES dim_tiempo,
 sk_estudiante integer NOT NULL REFERENCES dim_estudiante,
 sk_carrera integer NOT NULL REFERENCES dim_carrera,
 sk_cohorte integer NOT NULL REFERENCES dim_cohorte,
 sk_curso integer NOT NULL REFERENCES dim_curso,
 sk_sede integer NOT NULL REFERENCES dim_sede,
 sk_horario integer NOT NULL REFERENCES dim_horario,
 sk_docente integer NOT NULL REFERENCES dim_docente,
 sk_modalidad integer NOT NULL REFERENCES dim_modalidad,
 matricula smallint NOT NULL DEFAULT 1 CHECK(matricula=1),
 es_aprobado smallint NOT NULL CHECK(es_aprobado IN (0,1)),
 es_reprobado smallint NOT NULL CHECK(es_reprobado IN (0,1)),
 es_retirado smallint NOT NULL CHECK(es_retirado IN (0,1)),
 nota numeric(5,2) CHECK(nota IS NULL OR nota BETWEEN 0 AND 100),
 creditos_aprobados smallint NOT NULL DEFAULT 0 CHECK(creditos_aprobados >= 0),
 CHECK(es_aprobado+es_reprobado+es_retirado <= 1));
 
-- Hecho 2: una fila por grupo ofertado
CREATE TABLE fact_oferta (
 id_grupo_origen integer PRIMARY KEY,
 numero_grupo smallint NOT NULL CHECK(numero_grupo > 0),
 sk_tiempo integer NOT NULL REFERENCES dim_tiempo,
 sk_curso integer NOT NULL REFERENCES dim_curso,
 sk_sede integer NOT NULL REFERENCES dim_sede,
 sk_horario integer NOT NULL REFERENCES dim_horario,
 sk_docente integer NOT NULL REFERENCES dim_docente,
 sk_modalidad integer NOT NULL REFERENCES dim_modalidad,
 grupos smallint NOT NULL DEFAULT 1 CHECK(grupos=1),
 capacidad_corte smallint NOT NULL CHECK(capacidad_corte > 0),
 matriculados smallint NOT NULL CHECK(matriculados >= 0),
 CHECK(matriculados <= capacidad_corte));
 
-- Hecho 3: una fila por solicitud de cupo
CREATE TABLE fact_solicitud (
 id_solicitud_origen integer PRIMARY KEY,
 sk_tiempo integer NOT NULL REFERENCES dim_tiempo,
 sk_curso integer NOT NULL REFERENCES dim_curso,
 sk_sede integer NOT NULL REFERENCES dim_sede,
 sk_horario integer NOT NULL REFERENCES dim_horario,
 solicitudes smallint NOT NULL DEFAULT 1 CHECK(solicitudes=1),
 es_asignada smallint NOT NULL CHECK(es_asignada IN (0,1)),
 es_sin_cupo smallint NOT NULL CHECK(es_sin_cupo IN (0,1)),
 es_no_elegible smallint NOT NULL CHECK(es_no_elegible IN (0,1)),
 es_desistida smallint NOT NULL CHECK(es_desistida IN (0,1)),
 CHECK(es_asignada+es_sin_cupo+es_no_elegible+es_desistida = 1));
COMMIT;